name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
        working-directory: /PyPI/Package

      - name: Build package
        run: python -m build
        working-directory: /PyPI/Package

      - name: Publish package to PyPI
        run: python -m twine upload dist/*
        working-directory: /PyPI/Package
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
