name: Update WebUI Binaries

on:
  push:
    branches:
      - main

env:
  WRAPPER_WEBUI_BIN_PATH: PyPI/Package/src/webui

jobs:
  update-webui-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Install Tools
        continue-on-error: true
        run: |
          sudo apt-get install -y wget unzip tar git findutils

      - name: Download WebUI Archives
        run: |
          mkdir -p TempArchives
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-linux-clang-x64.zip -O TempArchives/webui-linux-clang-x64.zip
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-linux-gcc-arm.zip -O TempArchives/webui-linux-gcc-arm.zip
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-linux-gcc-arm64.zip -O TempArchives/webui-linux-gcc-arm64.zip
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-linux-gcc-x64.zip -O TempArchives/webui-linux-gcc-x64.zip
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-macos-clang-arm64.tar.gz -O TempArchives/webui-macos-clang-arm64.tar.gz
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-macos-clang-x64.tar.gz -O TempArchives/webui-macos-clang-x64.tar.gz
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-windows-gcc-x64.zip -O TempArchives/webui-windows-gcc-x64.zip
          wget -q https://github.com/webui-dev/webui/releases/download/2.4.0/webui-windows-msvc-x64.zip -O TempArchives/webui-windows-msvc-x64.zip

      - name: Extract Archives
        run: |
          mkdir TempArchives/webui-linux-clang-x64
          mkdir TempArchives/webui-linux-gcc-arm
          mkdir TempArchives/webui-linux-gcc-arm64
          mkdir TempArchives/webui-linux-gcc-x64
          mkdir TempArchives/webui-windows-gcc-x64
          mkdir TempArchives/webui-windows-msvc-x64
          mkdir TempArchives/webui-macos-clang-arm64
          mkdir TempArchives/webui-macos-clang-x64
          unzip -q TempArchives/webui-linux-clang-x64.zip -d TempArchives/webui-linux-clang-x64
          unzip -q TempArchives/webui-linux-gcc-arm.zip -d TempArchives/webui-linux-gcc-arm
          unzip -q TempArchives/webui-linux-gcc-arm64.zip -d TempArchives/webui-linux-gcc-arm64
          unzip -q TempArchives/webui-linux-gcc-x64.zip -d TempArchives/webui-linux-gcc-x64
          unzip -q TempArchives/webui-windows-gcc-x64.zip -d TempArchives/webui-windows-gcc-x64
          unzip -q TempArchives/webui-windows-msvc-x64.zip -d TempArchives/webui-windows-msvc-x64
          tar -xzf TempArchives/webui-macos-clang-arm64.tar.gz -C TempArchives/webui-macos-clang-arm64
          tar -xzf TempArchives/webui-macos-clang-x64.tar.gz -C TempArchives/webui-macos-clang-x64

      - name: Copy Libs from Archives
        run: |
          mkdir TempOut
          mkdir TempOut/webui-linux-clang-x64
          mkdir TempOut/webui-linux-gcc-arm
          mkdir TempOut/webui-linux-gcc-arm64
          mkdir TempOut/webui-linux-gcc-x64
          mkdir TempOut/webui-windows-gcc-x64
          mkdir TempOut/webui-windows-msvc-x64
          mkdir TempOut/webui-macos-clang-arm64
          mkdir TempOut/webui-macos-clang-x64
          find TempArchives -type d -name 'debug' -exec rm -rf {} +
          find TempArchives/webui-linux-clang-x64 -type f -name 'webui-2.so' -exec cp {} TempOut/webui-linux-clang-x64 \; -quit
          find TempArchives/webui-linux-clang-x64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-linux-clang-x64 \; -quit
          find TempArchives/webui-linux-gcc-arm -type f -name 'webui-2.so' -exec cp {} TempOut/webui-linux-gcc-arm \; -quit
          find TempArchives/webui-linux-gcc-arm -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-linux-gcc-arm \; -quit
          find TempArchives/webui-linux-gcc-arm64 -type f -name 'webui-2.so' -exec cp {} TempOut/webui-linux-gcc-arm64 \; -quit
          find TempArchives/webui-linux-gcc-arm64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-linux-gcc-arm64 \; -quit
          find TempArchives/webui-linux-gcc-x64 -type f -name 'webui-2.so' -exec cp {} TempOut/webui-linux-gcc-x64 \; -quit
          find TempArchives/webui-linux-gcc-x64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-linux-gcc-x64 \; -quit
          find TempArchives/webui-windows-gcc-x64 -type f -name 'webui-2.dll' -exec cp {} TempOut/webui-windows-gcc-x64 \; -quit
          find TempArchives/webui-windows-gcc-x64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-windows-gcc-x64 \; -quit
          find TempArchives/webui-windows-msvc-x64 -type f -name 'webui-2.dll' -exec cp {} TempOut/webui-windows-msvc-x64 \; -quit
          find TempArchives/webui-windows-msvc-x64 -type f -name 'webui-2.lib' -exec cp {} TempOut/webui-windows-msvc-x64 \; -quit
          find TempArchives/webui-windows-msvc-x64 -type f -name 'webui-2-static.lib' -exec cp {} TempOut/webui-windows-msvc-x64 \; -quit
          find TempArchives/webui-macos-clang-arm64 -type f -name 'webui-2.dylib' -exec cp {} TempOut/webui-macos-clang-arm64 \; -quit
          find TempArchives/webui-macos-clang-arm64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-macos-clang-arm64 \; -quit
          find TempArchives/webui-macos-clang-x64 -type f -name 'webui-2.dylib' -exec cp {} TempOut/webui-macos-clang-x64 \; -quit
          find TempArchives/webui-macos-clang-x64 -type f -name 'libwebui-2-static.a' -exec cp {} TempOut/webui-macos-clang-x64 \; -quit

      - name: Copy Libs to Wrapper
        run: |
          cp -ru TempOut/* "$WRAPPER_WEBUI_BIN_PATH/"

      - name: Remove Temporary Archives
        run: |
          rm -rf TempArchives
          rm -rf TempOut

      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add "$WRAPPER_WEBUI_BIN_PATH/"
          git commit -m "Update WebUI binaries" || echo "No WebUI binaries changes to commit"
          git push
